"""`wyrm --compile` entry point: walk a parsed module's top-level statements,
then assemble the compiled `fn`/`class` text and any `native::block` sections
into one C source string.

The assembled file ends with a registration table - a `lang_builtin[]` naming
each compiled function with its arity - so a host embedding the module has
one symbol to reach for rather than a list of names to keep in step by hand.
That table is the *only* part of the output that needs anything from the
interpreter it isn't already given: installing it means a hook that appends
to the interpreter's own builtin table, which is a change on that side, not
this one. Everything else here compiles against what the interpreter already
exposes.

See DESIGN.md for the package's layout and each submodule's role.
"""
from wypoc import ast_nodes as ast

from .classes import compile_class
from .errors import err
from .functions import compile_fn
from .native_blocks import NATIVE_PORTIONS, is_native_block_call, parse_native_block_args
from .wtypes import c_ident

PREAMBLE = """\
/* Generated by wyrm --compile from module {module_name!r}.
 *
 * Each `fn` is one C function following the interpreter's native calling
 * convention: arguments in as a wyrm_value array, the result out through
 * `*out`, and `false` returned on failure with the error already recorded.
 * `{module_ident}_BUILTINS` at the bottom names them for registration.
 */
#include <stdbool.h>

#include "lang_internal.h"
"""


def compile_module(tree: ast.Program, module_name: str) -> str:
    """Compile a parsed wyrm module (which must `import native`) to C source.
    Raises `CompileError`, naming the construct, on anything outside the
    supported subset - never silently-wrong C."""
    if not any(isinstance(s, ast.Import) and s.path == ["native"] for s in tree.body):
        err(
            "module does not 'import native'; not eligible for --compile "
            "(only modules that opt in with 'import native' can be compiled)"
        )

    sections, fn_defs, class_defs, body_order = _walk_toplevel(tree)

    module_ident = c_ident(module_name)
    functions = {fn.name: fn for fn in fn_defs}

    compiled = []
    for kind, item in body_order:
        compiled.append(item if kind == "raw" else compile_fn(item, functions, module_ident))
    compiled.extend(compile_class(cls, module_ident) for cls in class_defs)

    protos = [
        f"bool w_{module_ident}_{fn.name}(wyrm_lang_vm* vm, wyrm_value* args, "
        f"wyrm_uword argc, wyrm_value* out);"
        for fn in fn_defs
    ]
    protos += [
        f"bool w_{module_ident}_{cls.name}(wyrm_lang_vm* vm, wyrm_patch_class** out);"
        for cls in class_defs
    ]

    parts = [PREAMBLE.format(module_name=module_name, module_ident=module_ident.upper())]
    for portion in ("HEADER", "TYPES", "CONSTANTS"):
        if sections[portion]:
            parts.append(f"/* {portion} */")
            parts.append("\n".join(sections[portion]))
            parts.append("")
    parts.append("/* PROTOS */")
    parts.extend(protos)
    if sections["PROTOS"]:
        parts.append("\n".join(sections["PROTOS"]))
    parts.append("")
    parts.append("/* FUNCTIONS */")
    parts.extend(compiled)
    parts.append(_registration_table(module_ident, fn_defs))
    return "\n".join(parts) + "\n"


def _walk_toplevel(tree: ast.Program):
    """Sort the module body into native sections, `fn`s, `class`es, and the
    source order the two emitted kinds have to keep among themselves (a raw
    FUNCTIONS block may define something a following `fn` uses)."""
    sections = {portion: [] for portion in NATIVE_PORTIONS}
    fn_defs, class_defs, body_order = [], [], []
    seen_names = set()

    for stmt in tree.body:
        if isinstance(stmt, ast.Import):
            if stmt.path != ["native"]:
                err(
                    f"import of '{'::'.join(stmt.path)}' not supported by --compile "
                    f"(one file at a time)", stmt,
                )
            continue
        if isinstance(stmt, (ast.FnDef, ast.ClassDef)):
            if stmt.name in seen_names:
                err(f"duplicate top-level definition of '{stmt.name}'", stmt)
            seen_names.add(stmt.name)
            if isinstance(stmt, ast.FnDef):
                fn_defs.append(stmt)
                body_order.append(("fn", stmt))
            else:
                class_defs.append(stmt)
            continue
        if isinstance(stmt, ast.ExprStmt) and isinstance(stmt.value, ast.Call) \
                and is_native_block_call(stmt.value):
            portion, inputs, outputs, body = parse_native_block_args(stmt.value)
            if portion not in NATIVE_PORTIONS:
                err(f"native::block() portion {portion!r} unknown; expected one of "
                    f"{NATIVE_PORTIONS}", stmt)
            if inputs or outputs:
                err("a top-level native::block() must have empty input/output lists", stmt)
            if portion == "FUNCTIONS":
                body_order.append(("raw", body))
            else:
                sections[portion].append(body)
            continue
        err(
            "top-level statement not supported by --compile "
            "(only 'fn'/'class' definitions and native::block() calls are allowed)", stmt,
        )
    return sections, fn_defs, class_defs, body_order


def _registration_table(module_ident: str, fn_defs) -> str:
    """The compiled functions as the interpreter's own builtin-table rows, so
    a host installs the module by walking one array. Arity is exact both
    ways: a compiled function takes the parameters it declared."""
    rows = [
        f'    {{ "{fn.name}", BI_PLAIN, {len(fn.params)}, {len(fn.params)}, '
        f"w_{module_ident}_{fn.name} }},"
        for fn in fn_defs
    ]
    body = "\n".join(rows) if rows else "    /* no functions */"
    return (
        "/* REGISTRATION */\n"
        f"const lang_builtin {module_ident.upper()}_BUILTINS[] = {{\n"
        f"{body}\n"
        "};\n"
        f"const unsigned {module_ident.upper()}_BUILTIN_COUNT =\n"
        f"    (unsigned)(sizeof({module_ident.upper()}_BUILTINS) / "
        f"sizeof({module_ident.upper()}_BUILTINS[0]));\n"
    )
