"""wyrm --compile entrypoint: walks a parsed module's top-level statements,
then assembles the compiled `fn`/`class` C text and native::block sections
into one C source string targeting the real wyrm VM calling convention.

See DESIGN.md for the package's overall layout and each submodule's role.
"""
from wypoc import ast_nodes as ast

from .calls import FORWARDER_SRC
from .classes import compile_class
from .errors import err
from .functions import compile_fn
from .native_blocks import NATIVE_PORTIONS, is_native_block_call, parse_native_block_args
from .wtypes import c_ident


def compile_module(tree: ast.Program, module_name: str) -> str:
    """Compile a parsed Wyrm module (must `import native`) into C source
    text targeting the real wyrm VM calling convention. Raises
    CompileError on anything outside the v1 narrow slice."""
    has_native_import = any(isinstance(s, ast.Import) and s.path == ["native"] for s in tree.body)
    if not has_native_import:
        err(
            "module does not 'import native'; not eligible for --compile "
            "(only modules that opt in with 'import native' can be compiled)"
        )

    sections = {p: [] for p in NATIVE_PORTIONS}
    functions_order = []  # [("fn", FnDef) | ("raw", c_text), ...] in source order
    fn_defs = []
    class_defs = []
    seen_names = set()

    for stmt in tree.body:
        if isinstance(stmt, ast.Import):
            if stmt.path != ["native"]:
                err(
                    f"import of '{'::'.join(stmt.path)}' not supported by --compile "
                    f"(v1 only compiles single-file modules)", stmt,
                )
            continue
        if isinstance(stmt, ast.FnDef):
            if stmt.name in seen_names:
                err(f"duplicate top-level definition of '{stmt.name}'", stmt)
            seen_names.add(stmt.name)
            fn_defs.append(stmt)
            functions_order.append(("fn", stmt))
            continue
        if isinstance(stmt, ast.ClassDef):
            if stmt.name in seen_names:
                err(f"duplicate top-level definition of '{stmt.name}'", stmt)
            seen_names.add(stmt.name)
            class_defs.append(stmt)
            continue
        if isinstance(stmt, ast.ExprStmt) and isinstance(stmt.value, ast.Call) and is_native_block_call(stmt.value):
            portion, inputs, outputs, body = parse_native_block_args(stmt.value)
            if portion not in NATIVE_PORTIONS:
                err(f"native::block() portion {portion!r} unknown; expected one of {NATIVE_PORTIONS}", stmt)
            if inputs or outputs:
                err("top-level native::block() must have empty input/output lists", stmt)
            if portion == "FUNCTIONS":
                functions_order.append(("raw", body))
            else:
                sections[portion].append(body)
            continue
        err(
            "top-level statement not supported by --compile "
            "(only 'fn'/'class' definitions and native::block() calls are allowed)", stmt,
        )

    module_ident = c_ident(module_name)
    functions = {fn.name: fn for fn in fn_defs}
    compiled = []
    chunk_protos = []
    uses_forwarder = False
    for kind, item in functions_order:
        if kind == "raw":
            compiled.append(item)
        else:
            chunk_texts, chunk_names, fn_uses_forwarder = compile_fn(item, functions, module_ident)
            uses_forwarder = uses_forwarder or fn_uses_forwarder
            compiled.extend(chunk_texts)
            chunk_protos.extend(f"static wyrm_exec_state {name}(wyrm_state* state);" for name in chunk_names)

    compiled_classes = [compile_class(cls, module_ident) for cls in class_defs]

    protos = [f"wyrm_exec_state w_{module_ident}_{fn.name}(wyrm_state* state);" for fn in fn_defs]
    protos.extend(f"wyrm_error w_{module_ident}_{cls.name}(wyrm_context* context, wyrm_class** out);" for cls in class_defs)
    protos.extend(chunk_protos)
    if uses_forwarder:
        protos.insert(0, "static wyrm_exec_state __wyrm_forward_result(wyrm_state* state);")

    parts = [
        f"/* Generated by wyrm --compile from module '{module_name}' */",
        "#include <wyrm.h>",
        "#include <stdbool.h>",
        "",
    ]
    for section, header in (("HEADER", None), ("TYPES", "TYPES"), ("CONSTANTS", "CONSTANTS")):
        if sections[section]:
            if header:
                parts.append(f"/* {header} */")
            parts.append("\n".join(sections[section]))
            parts.append("")
    parts.append("/* PROTOS */")
    parts.extend(protos)
    if sections["PROTOS"]:
        parts.append("\n".join(sections["PROTOS"]))
    parts.append("")
    parts.append("/* FUNCTIONS */")
    if uses_forwarder:
        parts.append(FORWARDER_SRC)
    parts.extend(compiled)
    parts.extend(compiled_classes)
    return "\n".join(parts) + "\n"
