"""compile_module(tree, module_path) -> one .py file's full source text.

Stage 1-4 subset: top-level FnDef/CoDef (plain and external `[Cls, ...]`),
ClassDef (single inheritance, slots, class-body methods/coroutines,
`init`), `import` (see imports.py/graph.py - only reachable through
compile_module_with_meta, which a CompileGraph supplies), plus top-level
VarDecl/Assign/ExprStmt/If/While. Decorated still raises CompileError -
it lands in a later implementation stage (see the plan's staged rollout),
not because it's deliberately excluded from the language.

A generated module's Python top level defines only classes/functions/
coroutines/imports - it has *no* wyrm-level side effects at plain `import`
time. Every top-level executable wyrm statement (var initializers, bare
expr statements) is instead emitted into `async def do_import(ctx) ->
None`, so nothing runs until something explicitly awaits do_import(ctx).

Import chaining is grouped rather than strictly interleaved at each
Import statement's own source position: every distinct imported module's
own do_import is awaited, in first-seen order, right after the
mark_loaded guard - before *any* of this module's own top-level code
(including its own message-table build) runs. This is a deliberate
simplification of "await exactly where the Import statement appeared"
(the plan's literal description) for code that (like every fixture so
far) declares its imports before using them - it guarantees every
dependency is fully loaded before this module's own top level runs.
"""
from wypoc import ast_nodes as ast

from .classes import compile_class, external_co_registrations, external_method_registrations
from .coroutines import compile_co
from .context import FnCtx, ModuleCtx
from .errors import err
from .functions import compile_fn
from .imports import resolve_import
from .naming import py_ident, wildcard_wrapper_name
from .statements import compile_stmt

PREAMBLE = '''"""Generated by wyrm --compile-py. Do not edit by hand."""
import asyncio
from dataclasses import dataclass, field
from typing import Any, ClassVar

from wypoc.compiler_py import engine
from wypoc.compiler_py.engine import (
    Context, Cursor, Machine, MessageTable, WyrmError, dispatch, is_error,
)
'''


def _message_arities(body) -> dict:
    """First pass: for every message name that has at least one `[Cls,
    ...]`-targeted overload anywhere in the module (an external fn or a
    class-body method), record the arity of the *first* one encountered in
    source order - matching the interpreter's register_overload, where a
    later-promoted plain fn's wildcard arity is "derived from whichever
    [Cls, ...] signature is triggering the promotion"."""
    arities = {}
    for stmt in body:
        if isinstance(stmt, (ast.FnDef, ast.CoDef)) and stmt.class_target is not None:
            arities.setdefault(stmt.name, len(stmt.class_target))
        elif isinstance(stmt, ast.ClassDef):
            for member in stmt.body:
                if isinstance(member, (ast.FnDef, ast.CoDef)):
                    arities.setdefault(member.name, 1)
    return arities


# Builtin classes that exist only for the interpreter's native decorator/
# reflection layer (see wyrm_builtins.install's docstring - `sexpr`/
# `AstRef`/`TreeBase` are one family: a definition's own quoted tree,
# read and rewritten at decorator-expansion time). There's no runtime
# representation of "a piece of wyrm source as a value" in this backend,
# so a `[TreeBase] name(...)` external method - always part of that same
# macro-engine, never a user type instantiated at runtime - is dead
# weight here exactly like an `_is_macro_only` fn, and would fail to
# compile anyway (its body invariably calls the also-unsupported `sexpr`
# builtin).
_REFLECTION_ONLY_CLASSES = {"TreeBase"}


def _is_macro_only(fndef) -> bool:
    if fndef.name.startswith("$"):
        return True
    # AstRef: unconditionally macro-only (see _REFLECTION_ONLY_CLASSES
    # above). Decorated: this specific fn/co's own decorator body never
    # ran during the pre-pass's eager top-level execution (see
    # decorators_pass._resolve, which leaves such a node unexpanded
    # rather than raising) - skip just this definition rather than
    # aborting the whole module, since a working program plainly doesn't
    # exercise it.
    return any(isinstance(n, (ast.AstRef, ast.Decorated))
               for stmt in fndef.body for n in stmt.walk())


def _is_top_level_macro_only(fndef) -> bool:
    """Like _is_macro_only, but also catches a plain top-level fn/co (no
    `[Cls, ...]` target) whose body references `this` - never legal to
    actually call (there's no receiver to bind `this` to outside a
    message/method body), so a working program never calls one at
    runtime; only ever reached as raw quoted material inside another
    macro-template's `::$ast`-read body, e.g. `_tmpl_opt` referenced via
    `_decode_opt`'s `_tmpl_opt::$ast`. Not applied inside a class body
    (see classes.py), where a `this` reference is always legitimate
    regardless of `class_target`."""
    if _is_macro_only(fndef):
        return True
    if fndef.class_target is not None:
        return False
    return any(isinstance(n, ast.ThisRef) for stmt in fndef.body for n in stmt.walk())


_PRELUDE_PATH = ("prelude",)


def _inject_prelude(modctx: ModuleCtx, graph):
    """Every module the interpreter loads gets corelib/prelude.wy's names
    (`co range(...)`, etc.) seeded into its scope before its own top level
    runs - populate_globals(module_ctx) runs for every Scope, not just the
    entry script's (see wyrm_eval_parse_tree.py's import_module). This is
    the compiled equivalent: a synthesized `import prelude::*`, injected
    before the module's own (real) imports are resolved, so a name it
    defines still wins on a collision (resolve_import runs in source
    order, and a later import_bindings write overwrites an earlier one -
    matching the interpreter, where a module-local definition shadows a
    prelude name of the same one). `prelude` resolves like any other
    module because corelib/ is wyrm_modules' own final search root (see
    its search_paths' fallback) - no special-casing needed in graph.py.
    Guarded against the prelude module compiling itself."""
    if graph is None or modctx.module_path == _PRELUDE_PATH:
        return
    resolve_import(modctx, ast.Import(list(_PRELUDE_PATH), wildcard=True), graph)


def _walk_toplevel(modctx: ModuleCtx, body, graph):
    """Classifies each top-level statement, collecting global-var names to
    pre-declare and compiling fn/class/import statements immediately;
    returns the list of top-level statements (in source order) that belong
    inside do_import."""
    _inject_prelude(modctx, graph)
    message_arity = _message_arities(body)
    do_import_stmts = []
    for stmt in body:
        if isinstance(stmt, ast.Import):
            resolve_import(modctx, stmt, graph)
            continue
        if isinstance(stmt, (ast.FnDef, ast.CoDef)) and stmt.class_target is not None \
                and any(c in _REFLECTION_ONLY_CLASSES for c in stmt.class_target):
            continue
        if isinstance(stmt, (ast.FnDef, ast.CoDef)) and _is_top_level_macro_only(stmt):
            # A `$`-named fn/co (e.g. `fn $token_kind(kind): ...`) or one
            # whose body reads `other_def::$ast` (another definition's own
            # quoted tree - AstRef) is a macro-template/macro-engine
            # helper, not a real callable: the only legal way to reference
            # one is `name::$ast`, and AstRef has no runtime meaning this
            # backend can give it (there's no tree-value representation in
            # generated Python). Both are consumed exclusively by a
            # decorator's native-interpreter macro expansion, which
            # already ran and fully resolved every Decorated node before
            # Python codegen ever sees this tree (see decorators_pass.py) -
            # no compiled code ever calls one of these directly, so it's
            # dead weight here, and would fail to compile anyway (they
            # freely reference `this`/other names only meaningful when the
            # interpreter inlines the template's body, not run standalone).
            continue
        if isinstance(stmt, ast.ClassDef):
            if stmt.name in modctx.classes:
                err(f"class '{stmt.name}' redeclared at module top level", stmt)
            modctx.public_names.add(stmt.name)
            modctx.add_body("")
            modctx.add_body(compile_class(modctx, stmt))
            continue
        if isinstance(stmt, ast.FnDef) and stmt.class_target is not None:
            modctx.add_body("")
            modctx.add_body(external_method_registrations(modctx, stmt))
            continue
        if isinstance(stmt, ast.FnDef):
            if stmt.name in modctx.toplevel_names:
                err(f"'{stmt.name}' redeclared at module top level", stmt)
            modctx.toplevel_names.add(stmt.name)
            modctx.public_names.add(stmt.name)
            modctx.add_body("")
            modctx.add_body(compile_fn(modctx, stmt))
            arity = message_arity.get(stmt.name)
            if arity is not None:
                # Promotion: this plain fn is also callable as name's
                # wildcard overload, matching whichever [Cls, ...] arity
                # first established the message (see _message_arities).
                # dispatch() calls every overload as (this, *args,
                # **kwargs) - the plain fn itself has no `this` parameter,
                # so register a this-discarding adapter instead of the fn.
                wrapper_name = wildcard_wrapper_name(stmt.name)
                fn_name = py_ident(stmt.name)
                modctx.add_body(
                    f"async def {wrapper_name}(wy_this, *args, **kwargs):\n"
                    f"    return await {fn_name}(*args, **kwargs)"
                )
                modctx.messages.append((stmt.name, (None,) * arity, wrapper_name))
            continue
        if isinstance(stmt, ast.CoDef) and stmt.class_target is not None:
            modctx.add_body("")
            modctx.add_body(external_co_registrations(modctx, stmt))
            continue
        if isinstance(stmt, ast.CoDef):
            # Unlike a plain fn, a plain co is never auto-promoted into a
            # same-named message's wildcard overload - the interpreter's
            # own register_overload only promotes an existing *Function*
            # binding (isinstance(existing, Function)), never a Coroutine.
            if stmt.name in modctx.toplevel_names:
                err(f"'{stmt.name}' redeclared at module top level", stmt)
            modctx.toplevel_names.add(stmt.name)
            modctx.public_names.add(stmt.name)
            modctx.add_body("")
            modctx.add_body(compile_co(modctx, stmt))
            continue
        if isinstance(stmt, ast.Decorated):
            err("decorators are not yet supported by --compile-py", stmt)
        if isinstance(stmt, ast.VarDecl):
            for target in stmt.targets:
                if not isinstance(target, ast.VarTarget):
                    err("unsupported top-level var target", target)
                name = py_ident(target.name)
                if name in modctx.var_names:
                    err(f"'{target.name}' redeclared at module top level", target)
                modctx.var_names.add(name)
                modctx.public_names.add(target.name)
                modctx.add_body(f"{name} = None")
            do_import_stmts.append(stmt)
            continue
        if isinstance(stmt, ast.WithSimple):
            name = py_ident(stmt.name)
            if name in modctx.var_names:
                err(f"'{stmt.name}' redeclared at module top level", stmt)
            modctx.var_names.add(name)
            modctx.public_names.add(stmt.name)
            modctx.add_body(f"{name} = None")
            do_import_stmts.append(stmt)
            continue
        if isinstance(stmt, ast.WithBlock):
            for binding in stmt.bindings:
                name = py_ident(binding.name)
                if name in modctx.var_names:
                    err(f"'{binding.name}' redeclared at module top level", binding)
                modctx.var_names.add(name)
                modctx.public_names.add(binding.name)
                modctx.add_body(f"{name} = None")
            do_import_stmts.append(stmt)
            continue
        if isinstance(stmt, (ast.Assign, ast.ExprStmt, ast.If, ast.While, ast.For, ast.Pass)):
            do_import_stmts.append(stmt)
            continue
        err("top-level statement not supported by --compile-py", stmt)
    return do_import_stmts


def _sig_repr(signature: tuple) -> str:
    return "(" + ", ".join(s if s is not None else "None" for s in signature) + \
        ("," if len(signature) == 1 else "") + ")"


def _compile_do_import(modctx: ModuleCtx, do_import_stmts, global_names):
    fnctx = FnCtx(modctx=modctx)
    fnctx.emit("if not ctx.machine.mark_loaded(__name__):")
    fnctx.indent += 1
    fnctx.emit("return")
    fnctx.indent -= 1
    if global_names:
        fnctx.emit(f"global {', '.join(sorted(global_names))}")
    for dotted, _is_static in modctx.imports:
        fnctx.emit(f"await {dotted}.do_import(ctx)")
    fnctx.emit("_TABLE = MessageTable(__name__)")
    for dotted, is_static in modctx.imports:
        if is_static:
            fnctx.emit(f"_TABLE.merge({dotted}._TABLE)")
    for name, signature, fn_name in modctx.messages:
        fnctx.emit(f"_TABLE.register({name!r}, {_sig_repr(signature)}, {fn_name})")
    if not do_import_stmts:
        fnctx.emit("pass")
    else:
        for stmt in do_import_stmts:
            compile_stmt(fnctx, stmt)
    header = "async def do_import(ctx: Context) -> None:"
    return "\n".join([header] + fnctx.lines)


def _assemble(modctx: ModuleCtx, do_import_stmts) -> str:
    global_names = set(modctx.var_names) | {"_TABLE"}
    do_import_src = _compile_do_import(modctx, do_import_stmts, global_names)

    parts = [PREAMBLE]
    if modctx.header_lines:
        parts.append("\n".join(modctx.header_lines))
    parts.append("_TABLE = None")
    if modctx.body_lines:
        parts.append("\n".join(modctx.body_lines))
    parts.append("")
    parts.append(do_import_src)
    return "\n\n".join(p for p in parts if p != "") + "\n"


def compile_module(tree: ast.Program, module_path: tuple = (), graph=None) -> str:
    modctx = ModuleCtx(module_path=module_path)
    do_import_stmts = _walk_toplevel(modctx, tree.body, graph)
    return _assemble(modctx, do_import_stmts)


def compile_module_with_meta(tree: ast.Program, module_path: tuple, graph) -> tuple:
    """Like compile_module, but also returns the module's public_names -
    the raw wyrm top-level fn/class/var names another module's wildcard
    import can pull from. Used by graph.py; graph is required (not
    optional) here since this is only ever called while compiling one node
    of a transitive-import walk."""
    modctx = ModuleCtx(module_path=module_path)
    do_import_stmts = _walk_toplevel(modctx, tree.body, graph)
    return _assemble(modctx, do_import_stmts), set(modctx.public_names)


def compile_entry_module(tree: ast.Program, entry_name: str, graph=None) -> str:
    """Like compile_module, but appends the `if __name__ == "__main__":`
    driver an entry script gets (constructs a Machine/Context, runs an
    asyncio loop, awaits its own do_import).

    Also seeds the module global `__ARGS` compiles to (`wy___ARGS`) from
    `sys.argv[1:]` - the compiled equivalent of the interpreter's own
    `expose(ctx, "__ARGS", tuple(script_args))` (see cli.py's `main`).
    `__ARGS` is only ever read by the entry script itself (nothing so far
    ports a library module that reads it), so seeding it once here, rather
    than threading it through `do_import`'s signature, covers every case."""
    source = compile_module(tree, module_path=(), graph=graph)
    main_block = (
        "\n"
        "def _main() -> None:\n"
        "    import sys\n"
        "    global wy___ARGS\n"
        "    wy___ARGS = tuple(sys.argv[1:])\n"
        "    machine = Machine()\n"
        "    ctx = machine.root_context()\n"
        "    asyncio.run(do_import(ctx))\n"
        "\n"
        "\n"
        'if __name__ == "__main__":\n'
        "    _main()\n"
    )
    return source + main_block
