"""Writes a CompileGraph's compiled modules, plus the entry script, to an
output directory tree: `output_dir/wyrm/...` mirrors wyrm module-space
1:1 (a namespace package whose own root `__init__.py` just re-exports the
engine's runtime names), and `output_dir/<entry_name>.py` sits *outside*
`wyrm/`, as a sibling - see the plan's "Entry script placement" decision.
"""
import os

_ROOT_INIT = (
    '"""Generated by wyrm --compile-py - re-exports the runtime library '
    'every generated module imports from."""\n'
    "from wypoc.compiler_py.engine import Context, Cursor, Machine, dispatch\n"
)

_PACKAGE_INIT = '"""Generated by wyrm --compile-py."""\n'


def write_tree(graph, entry_source: str, entry_name: str, output_dir: str) -> None:
    wyrm_root = os.path.join(output_dir, "wyrm")
    os.makedirs(wyrm_root, exist_ok=True)
    with open(os.path.join(wyrm_root, "__init__.py"), "w", encoding="utf-8") as f:
        f.write(_ROOT_INIT)

    for compiled in graph.by_path.values():
        segs = compiled.path_segments
        if compiled.is_package:
            package_dir = os.path.join(wyrm_root, *segs)
            os.makedirs(package_dir, exist_ok=True)
            dest = os.path.join(package_dir, "__init__.py")
        else:
            package_dir = os.path.join(wyrm_root, *segs[:-1])
            os.makedirs(package_dir, exist_ok=True)
            dest = os.path.join(package_dir, f"{segs[-1]}.py")
        with open(dest, "w", encoding="utf-8") as f:
            f.write(compiled.source)

    with open(os.path.join(output_dir, f"{entry_name}.py"), "w", encoding="utf-8") as f:
        f.write(entry_source)
